return {
    name = "Colorblind Blind",

    ghostDragging = Color3.fromRGB(255, 255, 255),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(255, 255, 255),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(20, 20, 25),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(0, 0, 0),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(14, 14, 18),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(225, 225, 230),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(50, 50, 58),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(225, 225, 230),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(105, 105, 115),
    searchBoxText = Color3.fromRGB(225, 225, 230),

    userProfile = Color3.fromRGB(50, 50, 58),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(225, 225, 230),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(225, 225, 230),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(225, 225, 230),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(225, 225, 230),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(50, 50, 58),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(20, 20, 25),
    panelTransparency = 1,

    header = Color3.fromRGB(225, 225, 230),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(225, 225, 230),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(50, 50, 58),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(50, 50, 58),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(50, 50, 58),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(50, 50, 58),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(0, 0, 0),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(225, 225, 230),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(20, 20, 25),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(0, 0, 0),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(0, 0, 0),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(180, 180, 190),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(225, 225, 230),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(225, 225, 230),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(105, 105, 115)
}
