return {
    name = "Doom One",

    ghostDragging = Color3.fromRGB(255, 255, 255),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(255, 255, 255),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(40, 44, 52),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(0, 0, 0),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(33, 37, 44),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(187, 194, 207),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(76, 82, 96),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(187, 194, 207),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(130, 138, 152),
    searchBoxText = Color3.fromRGB(187, 194, 207),

    userProfile = Color3.fromRGB(76, 82, 96),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(187, 194, 207),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(187, 194, 207),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(187, 194, 207),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(187, 194, 207),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(76, 82, 96),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(40, 44, 52),
    panelTransparency = 1,

    header = Color3.fromRGB(187, 194, 207),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(187, 194, 207),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(76, 82, 96),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(76, 82, 96),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(76, 82, 96),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(76, 82, 96),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(25, 28, 34),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(187, 194, 207),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(40, 44, 52),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(25, 28, 34),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(0, 0, 0),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(81, 175, 239),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(187, 194, 207),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(187, 194, 207),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(130, 138, 152)
}
