return {
    name = "Duskfox",

    ghostDragging = Color3.fromRGB(255, 255, 255),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(255, 255, 255),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(35, 32, 48),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(0, 0, 0),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(28, 25, 40),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(230, 225, 240),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(75, 70, 95),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(230, 225, 240),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(125, 120, 145),
    searchBoxText = Color3.fromRGB(230, 225, 240),

    userProfile = Color3.fromRGB(75, 70, 95),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(230, 225, 240),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(230, 225, 240),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(230, 225, 240),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(230, 225, 240),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(75, 70, 95),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(35, 32, 48),
    panelTransparency = 1,

    header = Color3.fromRGB(230, 225, 240),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(230, 225, 240),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(75, 70, 95),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(75, 70, 95),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(75, 70, 95),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(75, 70, 95),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(22, 20, 32),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(230, 225, 240),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(35, 32, 48),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(22, 20, 32),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(0, 0, 0),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(200, 130, 190),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(230, 225, 240),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(230, 225, 240),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(125, 120, 145)
}
