return {
    name = "Everforest",

    ghostDragging = Color3.fromRGB(211, 198, 170),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(211, 198, 170),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(45, 53, 59),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(30, 35, 38),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(39, 46, 51),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(211, 198, 170),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(167, 192, 128),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(211, 198, 170),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(133, 146, 137),
    searchBoxText = Color3.fromRGB(211, 198, 170),

    userProfile = Color3.fromRGB(167, 192, 128),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(211, 198, 170),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(211, 198, 170),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(211, 198, 170),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(211, 198, 170),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(167, 192, 128),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(52, 63, 68),
    panelTransparency = 1,

    header = Color3.fromRGB(211, 198, 170),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(211, 198, 170),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(167, 192, 128),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(167, 192, 128),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(167, 192, 128),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(167, 192, 128),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(79, 88, 94),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(211, 198, 170),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(52, 63, 68),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(79, 88, 94),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(30, 35, 38),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(127, 187, 179),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(211, 198, 170),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(211, 198, 170),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(133, 146, 137)
}
