return {
    name = "GitHub Dark",

    ghostDragging = Color3.fromRGB(240, 246, 252),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(240, 246, 252),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(13, 17, 23),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(0, 0, 0),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(22, 27, 34),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(240, 246, 252),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(139, 148, 158),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(240, 246, 252),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(110, 118, 129),
    searchBoxText = Color3.fromRGB(240, 246, 252),

    userProfile = Color3.fromRGB(139, 148, 158),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(240, 246, 252),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(240, 246, 252),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(240, 246, 252),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(240, 246, 252),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(139, 148, 158),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(13, 17, 23),
    panelTransparency = 1,

    header = Color3.fromRGB(240, 246, 252),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(240, 246, 252),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(139, 148, 158),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(139, 148, 158),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(139, 148, 158),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(139, 148, 158),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(0, 0, 0),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(240, 246, 252),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(13, 17, 23),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(48, 54, 61),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(0, 0, 0),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(47, 129, 247),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(240, 246, 252),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(240, 246, 252),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(110, 118, 129)
}
