return {
    name = "Hacker News",

    ghostDragging = Color3.fromRGB(255, 255, 255),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(255, 255, 255),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(35, 30, 25),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(0, 0, 0),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(27, 23, 19),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(240, 230, 220),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(70, 60, 50),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(240, 230, 220),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(125, 110, 95),
    searchBoxText = Color3.fromRGB(240, 230, 220),

    userProfile = Color3.fromRGB(70, 60, 50),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(240, 230, 220),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(240, 230, 220),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(240, 230, 220),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(240, 230, 220),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(70, 60, 50),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(35, 30, 25),
    panelTransparency = 1,

    header = Color3.fromRGB(240, 230, 220),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(240, 230, 220),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(70, 60, 50),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(70, 60, 50),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(70, 60, 50),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(70, 60, 50),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(0, 0, 0),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(240, 230, 220),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(35, 30, 25),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(0, 0, 0),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(0, 0, 0),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(255, 102, 0),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(240, 230, 220),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(240, 230, 220),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(125, 110, 95)
}
