return {
    name = "Havn Light",

    ghostDragging = Color3.fromRGB(0, 0, 0),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(0, 0, 0),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(240, 245, 247),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(50, 90, 105),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(228, 235, 240),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(25, 45, 55),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(145, 165, 175),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(25, 45, 55),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(135, 155, 165),
    searchBoxText = Color3.fromRGB(25, 45, 55),

    userProfile = Color3.fromRGB(145, 165, 175),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(25, 45, 55),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(25, 45, 55),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(25, 45, 55),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(25, 45, 55),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(145, 165, 175),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(240, 245, 247),
    panelTransparency = 1,

    header = Color3.fromRGB(25, 45, 55),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(25, 45, 55),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(145, 165, 175),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(145, 165, 175),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(145, 165, 175),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(145, 165, 175),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(50, 90, 105),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(25, 45, 55),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(240, 245, 247),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(50, 90, 105),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(50, 90, 105),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(30, 150, 140),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(25, 45, 55),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(25, 45, 55),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(135, 155, 165)
}
