return {
    name = "Light+",

    ghostDragging = Color3.fromRGB(0, 0, 0),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(0, 0, 0),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(228, 232, 238),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(180, 180, 190),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(200, 205, 215),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(28, 30, 36),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(85, 88, 95),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(28, 30, 36),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(110, 113, 120),
    searchBoxText = Color3.fromRGB(28, 30, 36),

    userProfile = Color3.fromRGB(85, 88, 95),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(28, 30, 36),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(28, 30, 36),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(28, 30, 36),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(28, 30, 36),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(85, 88, 95),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(228, 232, 238),
    panelTransparency = 1,

    header = Color3.fromRGB(28, 30, 36),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(28, 30, 36),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(85, 88, 95),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(85, 88, 95),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(85, 88, 95),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(85, 88, 95),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(130, 132, 140),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(28, 30, 36),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(228, 232, 238),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(130, 132, 140),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(180, 180, 190),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(56, 150, 255),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(28, 30, 36),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(28, 30, 36),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(110, 113, 120)
}
