return {
    name = "Night Owl Light",

    ghostDragging = Color3.fromRGB(64, 69, 76),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(64, 69, 76),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(251, 251, 251),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(40, 40, 40),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(241, 242, 243),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(64, 69, 76),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(105, 111, 119),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(64, 69, 76),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(139, 145, 151),
    searchBoxText = Color3.fromRGB(64, 69, 76),

    userProfile = Color3.fromRGB(105, 111, 119),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(64, 69, 76),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(64, 69, 76),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(64, 69, 76),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(64, 69, 76),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(105, 111, 119),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(251, 251, 251),
    panelTransparency = 1,

    header = Color3.fromRGB(64, 69, 76),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(64, 69, 76),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(105, 111, 119),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(105, 111, 119),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(105, 111, 119),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(105, 111, 119),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(64, 69, 76),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(64, 69, 76),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(251, 251, 251),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(190, 193, 197),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(120, 124, 130),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(45, 103, 180),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(64, 69, 76),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(64, 69, 76),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(139, 145, 151)
}
