return {
    name = "Oceanic Next Light",

    ghostDragging = Color3.fromRGB(0, 0, 0),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(0, 0, 0),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(235, 240, 245),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(40, 55, 75),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(222, 230, 238),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(30, 45, 60),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(150, 165, 180),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(30, 45, 60),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(140, 155, 170),
    searchBoxText = Color3.fromRGB(30, 45, 60),

    userProfile = Color3.fromRGB(150, 165, 180),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(30, 45, 60),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(30, 45, 60),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(30, 45, 60),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(30, 45, 60),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(150, 165, 180),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(235, 240, 245),
    panelTransparency = 1,

    header = Color3.fromRGB(30, 45, 60),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(30, 45, 60),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(150, 165, 180),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(150, 165, 180),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(150, 165, 180),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(150, 165, 180),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(175, 185, 195),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(30, 45, 60),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(235, 240, 245),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(175, 185, 195),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(40, 55, 75),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(50, 110, 180),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(30, 45, 60),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(30, 45, 60),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(140, 155, 170)
}
