return {
    name = "One Light Pro (Light)",

    ghostDragging = Color3.fromRGB(0, 0, 0),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(0, 0, 0),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(250, 250, 250),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(40, 40, 40),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(216, 221, 234),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(56, 58, 66),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(64, 120, 242),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(56, 58, 66),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(141, 147, 167),
    searchBoxText = Color3.fromRGB(56, 58, 66),

    userProfile = Color3.fromRGB(64, 120, 242),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(56, 58, 66),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(56, 58, 66),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(56, 58, 66),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(56, 58, 66),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(64, 120, 242),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(250, 250, 250),
    panelTransparency = 1,

    header = Color3.fromRGB(56, 58, 66),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(56, 58, 66),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(64, 120, 242),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(64, 120, 242),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(64, 120, 242),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(64, 120, 242),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(23, 46, 91),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(56, 58, 66),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(250, 250, 250),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(138, 138, 138),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(108, 108, 108),
    dropdownShadowTransparency = 0.5,

    accent = Color3.fromRGB(64, 120, 242),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(56, 58, 66),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(56, 58, 66),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(141, 147, 167)
}
