return {
    name = "Redpanda Light",

    ghostDragging = Color3.fromRGB(0, 0, 0),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(0, 0, 0),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(245, 235, 230),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(110, 80, 70),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(240, 230, 224),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(40, 25, 20),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(180, 150, 140),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(40, 25, 20),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(165, 135, 125),
    searchBoxText = Color3.fromRGB(40, 25, 20),

    userProfile = Color3.fromRGB(180, 150, 140),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(40, 25, 20),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(40, 25, 20),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(40, 25, 20),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(40, 25, 20),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(180, 150, 140),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(245, 235, 230),
    panelTransparency = 1,

    header = Color3.fromRGB(40, 25, 20),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(40, 25, 20),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(180, 150, 140),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(180, 150, 140),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(180, 150, 140),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(180, 150, 140),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(110, 80, 70),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(40, 25, 20),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(245, 235, 230),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(110, 80, 70),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(110, 80, 70),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(193, 51, 26),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(40, 25, 20),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(40, 25, 20),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(165, 135, 125)
}
