return {
    name = "Solarized Light",

    ghostDragging = Color3.fromRGB(0, 43, 54),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(0, 43, 54),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(253, 246, 227),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(0, 43, 54),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(238, 232, 213),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(0, 43, 54),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(88, 110, 117),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(0, 43, 54),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(147, 161, 161),
    searchBoxText = Color3.fromRGB(0, 43, 54),

    userProfile = Color3.fromRGB(88, 110, 117),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(0, 43, 54),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(0, 43, 54),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(0, 43, 54),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(0, 43, 54),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(88, 110, 117),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(253, 246, 227),
    panelTransparency = 1,

    header = Color3.fromRGB(0, 43, 54),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(0, 43, 54),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(88, 110, 117),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(88, 110, 117),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(88, 110, 117),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(88, 110, 117),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(0, 43, 54),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(0, 43, 54),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(253, 246, 227),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(147, 161, 161),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(88, 110, 117),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(38, 139, 210),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(0, 43, 54),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(0, 43, 54),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(147, 161, 161)
}
