return {
    name = "Tokyo Night Day",

    ghostDragging = Color3.fromRGB(0, 0, 0),
    ghostDraggingTransparency = 0.5,
    ghostDraggingBorder = Color3.fromRGB(0, 0, 0),
    ghostDraggingBorderTransparency = 0,

    background = Color3.fromRGB(225, 226, 231),
    backgroundTransparency = 0.05,

    shadow = Color3.fromRGB(80, 85, 110),
    shadowTransparency = 0.5,

    sidebar = Color3.fromRGB(210, 214, 226),
    sidebarTransparency = 0.7,

    titleBar = Color3.fromRGB(52, 59, 88),
    titleBarTransparency = 0,

    searchBar = Color3.fromRGB(150, 160, 190),
    searchBarTransparency = 0.9,
    searchIcon = Color3.fromRGB(52, 59, 88),
    searchIconTransparency = 0.5,
    searchBoxPlaceholder = Color3.fromRGB(140, 150, 180),
    searchBoxText = Color3.fromRGB(52, 59, 88),

    userProfile = Color3.fromRGB(150, 160, 190),
    userProfileHoverTransparency = 0.94,
    userProfileTransparency = 1,
    userImage = Color3.fromRGB(52, 59, 88),
    userImageTransparency = 0.92,
    username = Color3.fromRGB(52, 59, 88),
    usernameTransparency = 0,
    userDescription = Color3.fromRGB(52, 59, 88),
    userDescriptionTransparency = 0.6,

    group = Color3.fromRGB(52, 59, 88),
    groupTransparency = 0.6,

    tab = Color3.fromRGB(150, 160, 190),
    tabTransparency = 1,
    tabHoverTransparency = 0.95,
    tabActiveTransparency = 0.9,
    tabActiveHoverTransparency = 0.85,

    panel = Color3.fromRGB(225, 226, 231),
    panelTransparency = 1,

    header = Color3.fromRGB(52, 59, 88),
    headerTransparency = 0.5,
    headerActive = Color3.fromRGB(52, 59, 88),
    headerActiveTransparency = 0,

    scrollBarImage = Color3.fromRGB(150, 160, 190),
    scrollBarImageTransparency = 0.9,

    element = Color3.fromRGB(150, 160, 190),
    elementTransparency = 0.9,
    elementHoverTransparency = 0.85,

    track = Color3.fromRGB(150, 160, 190),
    trackTransparency = 0.6,

    thumb = Color3.fromRGB(255, 255, 255),
    thumbTransparency = 0.5,
    thumbActiveTransparency = 0,

    option = Color3.fromRGB(150, 160, 190),
    optionTransparency = 0.9,
    optionBorder = Color3.fromRGB(180, 185, 200),
    optionBorderTransparency = 0.88,
    optionHoverTransparency = 0.95,
    optionHoverActiveTransparency = 0.85,
    optionNotActiveTransparency = 1,
    optionText = Color3.fromRGB(52, 59, 88),
    optionTextTransparency = 0,
    optionTextNotActiveTransparency = 0.5,

    dropdown = Color3.fromRGB(225, 226, 231),
    dropdownTransparency = 0.1,
    dropdownBorder = Color3.fromRGB(180, 185, 200),
    dropdownBorderTransparency = 0.5,
    dropdownShadow = Color3.fromRGB(80, 85, 110),
    dropdownShadowTransparency = 0.7,

    accent = Color3.fromRGB(52, 84, 180),
    accentTransparency = 0.2,

    primary = Color3.fromRGB(52, 59, 88),
    primaryTransparency = 0,

    secondary = Color3.fromRGB(52, 59, 88),
    secondaryTransparency = 0.5,

    placeHolder = Color3.fromRGB(140, 150, 180)
}
